# Generated by Django 3.2 on 2024-09-23 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0, message='Год не может быть меньше нуля'), django.core.validators.MaxValueValidator(2024, message='Год не может быть из будущего')], verbose_name='год выхода'),
        ),
    ]
